name: ${project.artifactId}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}
authors: [ Siroshun09 ]
api-version: "1.19"
folia-supported: true

permissions:
  togglebeaconparticle.command:
    default: true

commands:
  togglebeaconparticle:
    aliases: [ "tbp" ]
