name: Java CI
on: [ push, pull_request ]

jobs:
  build:
    uses: okocraft/workflows/.github/workflows/maven.yml@v1
    with:
      java-version: '21'
      package-name: ToggleBeaconParticle-Build-${{ github.run_number }}
